
功用: 
  - id: type1
  - tags: 
    - 网站
    - 微信运营
    - 微信网站（H5）
    - AR增强现实
    - VR虚拟现实
    - iPad售楼系统

用途:  
  - id: type2
  - tags:
    - 广告营销
    - 投标汇报

业态:
  - id: type3
  - tags:
    - 公建
    - 住宅
    - 商业
    - 办公
    - 别墅
    - 公寓 

角度:  
  - id: type4
  - tags:
    - 人视
    - 鸟瞰

品牌:  
  - id: type5
  - tags:
    - 绿地
    - 万科
    - 金地
    - 绿城
    - 保利
    - 新鸿基
    - 远洋
    - 瑞安
    - 和黄
    - 其他

技法:  
  - id: type6
  - tags:
    - 写意
    - 写实
    - 三维
    - 实拍

建筑风格:
  - id: type7
  - tags:
    - 古典
    - 现代
    - 中式
    - Artdeco
    - 法式
    - 英式
    - 西班牙式
    - 意式
    - 北美
    - 新古典
    - 新中式
    - 莱特
    - 现代简约
